---
title: "mpg Dataset with interactivity"
output: html_notebook
---
```{r}
library(ggplot2)
library(plotly)
head(mpg, 10)
count(mpg, manufacturer)
# Stacked Bar Chart
p1 <- ggplot(mpg, aes(x = class, fill = drv)) + geom_bar(position = "stack")
ggplotly(p1)
```
```{r}
# Grouped Bar Chart
p2 <- ggplot(mpg, aes(x = class, fill = drv)) + geom_bar(position = position_dodge(preserve = "single"))
ggplotly(p2)
```
```{r}
# Segmented Bar Chart
library(dplyr)
library(scales)
plotdata <- mpg %>% group_by(class, drv) %>% summarize(n = n()) %>% mutate(pct = n/sum(n), lbl = scales::percent(pct))
plotdata
p3 <- ggplot(plotdata, aes(x = factor(class, levels = c("2seater", "subcompact", "compact", "midsize", "minivan", "suv", "pickup")), y = pct, fill = factor(drv, levels = c("f", "r", "4"), labels = c("front-wheel", "rear-wheel", "4-wheel")))) 
p3 <- p3 + geom_bar(stat = "identity", position = "fill") + scale_y_continuous(breaks = seq(0, 1, .2), label = percent) + geom_text(aes(label = lbl), size = 3, position = position_stack(vjust = 0.5)) + scale_fill_brewer(palette = "Set2") + labs(y = "Percent", fill = "Drive Train", x = "Class", title = "Automobile Drive by Class") + theme_minimal()
p3
```
```{r}
# Ridgeline Graph
library(ggridges)
p4 <- ggplot(mpg, aes(x = cty, y = class, fill = class)) + geom_density_ridges() + theme_ridges() + labs(title = "City mileage by auto class")
p4
```
```{r}
# Scatter Plot
mean_hwy = mean(mpg$hwy)
mean_displ = mean(mpg$displ)
max_hwy = max(mpg$hwy)
min_displ = min(mpg$displ)
p5 <- ggplot(mpg, aes(x = displ, y = hwy, color = class, shape = factor(year))) + geom_point(size = 3, alpha = .75) + labs(title = "Displacement by Highway Mileage", x = "Engine Displacement (litres)", y = "Highway Miles per gallon") + theme_minimal()
p5 <- p5 + geom_hline(yintercept = mean_hwy, color = "darkred", linetype = "dashed") + ggplot2::annotate("text", min_displ, mean_hwy - 1, label = "Mean", color = "darkred") + geom_vline(xintercept = mean_displ, color = "darkred", linetype = "dashed") + ggplot2::annotate("text", mean_displ - .25, max_hwy, label = "Mean", color = "darkred")
ggplotly(p5)
```